"""
# Electric Load Center-Generator Specifications
"""
"""
Generator:InternalCombustionEngine
This generator model is the empirical model from the Building Loads and System Thermodynamics (BLAST) program. Engine performance curves are generated by fitting catalog data to second order polynomial equations. Three sets of coefficients are required.

Fields

rated_power_output [number]
electric_circuit_node_name [string]
minimum_part_load_ratio [number]
maximum_part_load_ratio [number]
optimum_part_load_ratio [number]
shaft_power_curve_name [string]
jacket_heat_recovery_curve_name [string]
lube_heat_recovery_curve_name [string]
total_exhaust_energy_curve_name [string]
exhaust_temperature_curve_name [string]
coefficient_1_of_u_factor_times_area_curve [number]
coefficient_2_of_u_factor_times_area_curve [number]
maximum_exhaust_flow_per_unit_of_power_output [number]
design_minimum_exhaust_temperature [number]
fuel_higher_heating_value [number]
design_heat_recovery_water_flow_rate [number] (Default: 0.0)
heat_recovery_inlet_node_name [string]
heat_recovery_outlet_node_name [string]
fuel_type [string] (Default: Diesel)
heat_recovery_maximum_temperature [number] (Default: 80.0)
Generator:CombustionTurbine
This generator model is the empirical model from the Building Loads and System Thermodynamics (BLAST) program. Generator performance curves are generated by fitting catalog data to second order polynomial equations. Three sets of coefficients are required.

Fields

rated_power_output [number]
electric_circuit_node_name [string]
minimum_part_load_ratio [number]
maximum_part_load_ratio [number]
optimum_part_load_ratio [number]
part_load_based_fuel_input_curve_name [string]
temperature_based_fuel_input_curve_name [string]
exhaust_flow_curve_name [string]
part_load_based_exhaust_temperature_curve_name [string]
temperature_based_exhaust_temperature_curve_name [string]
heat_recovery_lube_energy_curve_name [string]
coefficient_1_of_u_factor_times_area_curve [number]
coefficient_2_of_u_factor_times_area_curve [number]
maximum_exhaust_flow_per_unit_of_power_output [number]
design_minimum_exhaust_temperature [number]
design_air_inlet_temperature [number]
fuel_higher_heating_value [number]
design_heat_recovery_water_flow_rate [number] (Default: 0.0)
heat_recovery_inlet_node_name [string]
heat_recovery_outlet_node_name [string]
fuel_type [string] (Default: NaturalGas)
heat_recovery_maximum_temperature [number] (Default: 80.0)
outdoor_air_inlet_node_name [string]
Generator:MicroTurbine
MicroTurbine generators are small combustion turbines (e.g., 25kW to 500kW). The model calculates electrical power output, fuel use, standby and ancillary power. Energy recovery from exhaust air can be used to heat water.

Fields

reference_electrical_power_output [number]
minimum_full_load_electrical_power_output [number] (Default: 0.0)
maximum_full_load_electrical_power_output [number]
reference_electrical_efficiency_using_lower_heating_value [number]
reference_combustion_air_inlet_temperature [number] (Default: 15.0)
reference_combustion_air_inlet_humidity_ratio [number] (Default: 0.00638)
reference_elevation [number] (Default: 0.0)
electrical_power_function_of_temperature_and_elevation_curve_name [string]
electrical_efficiency_function_of_temperature_curve_name [string]
electrical_efficiency_function_of_part_load_ratio_curve_name [string]
fuel_type [string] (Default: NaturalGas)
fuel_higher_heating_value [number] (Default: 50000.0)
fuel_lower_heating_value [number] (Default: 45450.0)
standby_power [number] (Default: 0.0)
ancillary_power [number] (Default: 0.0)
ancillary_power_function_of_fuel_input_curve_name [string]
heat_recovery_water_inlet_node_name [string]
heat_recovery_water_outlet_node_name [string]
reference_thermal_efficiency_using_lower_heat_value [number] (Default: 0.0)
reference_inlet_water_temperature [number]
heat_recovery_water_flow_operating_mode [string] (Default: PlantControl)
reference_heat_recovery_water_flow_rate [number]
heat_recovery_water_flow_rate_function_of_temperature_and_power_curve_name [string]
thermal_efficiency_function_of_temperature_and_elevation_curve_name [string]
heat_recovery_rate_function_of_part_load_ratio_curve_name [string]
heat_recovery_rate_function_of_inlet_water_temperature_curve_name [string]
heat_recovery_rate_function_of_water_flow_rate_curve_name [string]
minimum_heat_recovery_water_flow_rate [number] (Default: 0.0)
maximum_heat_recovery_water_flow_rate [number] (Default: 0.0)
maximum_heat_recovery_water_temperature [number]
combustion_air_inlet_node_name [string]
combustion_air_outlet_node_name [string]
reference_exhaust_air_mass_flow_rate [number]
exhaust_air_flow_rate_function_of_temperature_curve_name [string]
exhaust_air_flow_rate_function_of_part_load_ratio_curve_name [string]
nominal_exhaust_air_outlet_temperature [number]
exhaust_air_temperature_function_of_temperature_curve_name [string]
exhaust_air_temperature_function_of_part_load_ratio_curve_name [string]
Generator:Photovoltaic
Describes an array of photovoltaic (PV) modules. A series of different PV arrays can be connected to a single electric load center (and inverter) by listing them all in an ElectricLoadCenter:Generator object. PV performance is taken from the referenced PhotovoltaicPerformance:* object. Array tilt, azimuth, and gross area are taken from the referenced building surface or shading surface. The array surface participates normally in all shading calculations.

Fields

surface_name [string]
photovoltaic_performance_object_type [string]
module_performance_name [string]
heat_transfer_integration_mode [string] (Default: Decoupled)
number_of_series_strings_in_parallel [number] (Default: 1.0)
number_of_modules_in_series [number] (Default: 1.0)
PhotovoltaicPerformance:Simple
Describes a simple model of photovoltaics that may be useful for early phase design analysis. In this model the user has direct access to the efficiency with which surfaces convert incident solar radiation to electricity and need not specify arrays of specific modules.

Fields

fraction_of_surface_area_with_active_solar_cells [number]
conversion_efficiency_input_mode [string]
value_for_cell_efficiency_if_fixed [number]
efficiency_schedule_name [string]
PhotovoltaicPerformance:EquivalentOne-Diode
Describes the performance characteristics of Photovoltaic (PV) modules to be modeled using an equivalent one-diode circuit. This model is also known as the 4- or 5-parameter TRNSYS model for photovoltaics.

Fields

cell_type [string]
number_of_cells_in_series [number] (Default: 36.0)
active_area [number] (Default: 0.89)
transmittance_absorptance_product [number] (Default: 0.95)
semiconductor_bandgap [number] (Default: 1.12)
shunt_resistance [number] (Default: 1000000.0)
short_circuit_current [number] (Default: 6.5)
open_circuit_voltage [number] (Default: 21.6)
reference_temperature [number] (Default: 25.0)
reference_insolation [number] (Default: 1000.0)
module_current_at_maximum_power [number] (Default: 5.9)
module_voltage_at_maximum_power [number] (Default: 17.0)
temperature_coefficient_of_short_circuit_current [number] (Default: 0.02)
temperature_coefficient_of_open_circuit_voltage [number] (Default: -0.079)
nominal_operating_cell_temperature_test_ambient_temperature [number] (Default: 20.0)
nominal_operating_cell_temperature_test_cell_temperature [number] (Default: 40.0)
nominal_operating_cell_temperature_test_insolation [number] (Default: 800.0)
module_heat_loss_coefficient [number] (Default: 30.0)
total_heat_capacity [number] (Default: 50000.0)
PhotovoltaicPerformance:Sandia
Describes performance input data needed for specific makes and models of production PV panels using the empirical coefficients assembled by Sandia National Laboratory.

Fields

active_area [number] (Default: 1.0)
number_of_cells_in_series [number] (Default: 1.0)
number_of_cells_in_parallel [number] (Default: 1.0)
short_circuit_current [number]
open_circuit_voltage [number]
current_at_maximum_power_point [number]
voltage_at_maximum_power_point [number]
sandia_database_parameter_aisc [number]
sandia_database_parameter_aimp [number]
sandia_database_parameter_c0 [number]
sandia_database_parameter_c1 [number]
sandia_database_parameter_bvoc0 [number]
sandia_database_parameter_mbvoc [number]
sandia_database_parameter_bvmp0 [number]
sandia_database_parameter_mbvmp [number]
diode_factor [number]
sandia_database_parameter_c2 [number]
sandia_database_parameter_c3 [number]
sandia_database_parameter_a0 [number]
sandia_database_parameter_a1 [number]
sandia_database_parameter_a2 [number]
sandia_database_parameter_a3 [number]
sandia_database_parameter_a4 [number]
sandia_database_parameter_b0 [number]
sandia_database_parameter_b1 [number]
sandia_database_parameter_b2 [number]
sandia_database_parameter_b3 [number]
sandia_database_parameter_b4 [number]
sandia_database_parameter_b5 [number]
sandia_database_parameter_delta_tc_ [number]
sandia_database_parameter_fd [number]
sandia_database_parameter_a [number]
sandia_database_parameter_b [number]
sandia_database_parameter_c4 [number]
sandia_database_parameter_c5 [number]
sandia_database_parameter_ix0 [number]
sandia_database_parameter_ixx0 [number]
sandia_database_parameter_c6 [number]
sandia_database_parameter_c7 [number]
Generator:PVWatts
Describes a simple set of inputs for an array of photovoltaic (PV) modules as described in the PVWatts software. A series of different PVWatts arrays can be connected to a single electric load center (preferably through an ElectricLoadCenter:Inverter:PVWatts). Array tilt and azimuth can be either specified on this object or taken from a referenced building surface or shading surface. If a surface is specified, the array participates normally in all shading calculations.

Fields

pvwatts_version [string]
dc_system_capacity [number]
module_type [string]
array_type [string]
system_losses [number] (Default: 0.14)
array_geometry_type [string] (Default: TiltAzimuth)
tilt_angle [number] (Default: 20.0)
azimuth_angle [number] (Default: 180.0)
surface_name [string]
ground_coverage_ratio [number] (Default: 0.4)
ElectricLoadCenter:Inverter:PVWatts
Electric power inverter to convert from direct current (DC) to alternating current (AC) in an electric load center that contains Generator:PVWatts objects. It implements the PVWatts inverter performance curves.

Fields

dc_to_ac_size_ratio [number] (Default: 1.1)
inverter_efficiency [number] (Default: 0.96)
Generator:FuelCell
This generator model is the FC model from IEA Annex 42

Fields

power_module_name [string]
air_supply_name [string]
fuel_supply_name [string]
water_supply_name [string]
auxiliary_heater_name [string]
heat_exchanger_name [string]
electrical_storage_name [string]
inverter_name [string]
stack_cooler_name [string]
Generator:FuelCell:PowerModule
Describe the core power module subsystem of a fuel cell power generator. This includes the fuel cell stack, fuel reformer, and whatever ancillary devices are included inside. If the model has multiple FC generators that are of the exact same type, then only one of these objects is needed and all the Generator:FuelCell objects can reference it.

Fields

efficiency_curve_mode [string]
efficiency_curve_name [string]
nominal_efficiency [number]
nominal_electrical_power [number]
number_of_stops_at_start_of_simulation [number]
cycling_performance_degradation_coefficient [number]
number_of_run_hours_at_beginning_of_simulation [number]
accumulated_run_time_degradation_coefficient [number]
run_time_degradation_initiation_time_threshold [number]
power_up_transient_limit [number]
power_down_transient_limit [number]
start_up_time [number]
start_up_fuel [number]
start_up_electricity_consumption [number]
start_up_electricity_produced [number]
shut_down_time [number]
shut_down_fuel [number]
shut_down_electricity_consumption [number]
ancillary_electricity_constant_term [number]
ancillary_electricity_linear_term [number]
skin_loss_calculation_mode [string]
zone_name [string]
skin_loss_radiative_fraction [number]
constant_skin_loss_rate [number]
skin_loss_u_factor_times_area_term [number]
skin_loss_quadratic_curve_name [string]
dilution_air_flow_rate [number]
stack_heat_loss_to_dilution_air [number]
dilution_inlet_air_node_name [string]
dilution_outlet_air_node_name [string]
minimum_operating_point [number]
maximum_operating_point [number]
Generator:FuelCell:AirSupply
Used to define details of the air supply subsystem for a fuel cell power generator.

Fields

air_inlet_node_name [string]
blower_power_curve_name [string]
blower_heat_loss_factor [number]
air_supply_rate_calculation_mode [string]
stoichiometric_ratio [number]
air_rate_function_of_electric_power_curve_name [string]
air_rate_air_temperature_coefficient [number]
air_rate_function_of_fuel_rate_curve_name [string]
air_intake_heat_recovery_mode [string]
air_supply_constituent_mode [string]
number_of_userdefined_constituents [number]
constituent_fractions [Array of {constituent_name, molar_fraction}]
Generator:FuelCell:WaterSupply
Used to provide details of the water supply subsystem for a fuel cell power generator. This water is used for steam reforming of the fuel and is not the same as the water used for thermal heat recovery.

Fields

reformer_water_flow_rate_function_of_fuel_rate_curve_name [string]
reformer_water_pump_power_function_of_fuel_rate_curve_name [string]
pump_heat_loss_factor [number]
water_temperature_modeling_mode [string]
water_temperature_reference_node_name [string]
water_temperature_schedule_name [string]
Generator:FuelCell:AuxiliaryHeater
Intended for modeling an auxiliary heater for a fuel cell power generator, however this portion of the model is not yet available. The program still requires one of these objects be included even though the data are not yet used (so that internal data structures can be allocated).

Fields

excess_air_ratio [number]
ancillary_power_constant_term [number]
ancillary_power_linear_term [number]
skin_loss_u_factor_times_area_value [number]
skin_loss_destination [string]
zone_name_to_receive_skin_losses [string]
heating_capacity_units [string]
maximum_heating_capacity_in_watts [number]
minimum_heating_capacity_in_watts [number]
maximum_heating_capacity_in_kmol_per_second [number]
minimum_heating_capacity_in_kmol_per_second [number]
Generator:FuelCell:ExhaustGasToWaterHeatExchanger
Describes the exhaust gas heat exchanger subsystem of a fuel cell power generator used to recovery thermal energy

Fields

heat_recovery_water_inlet_node_name [string]
heat_recovery_water_outlet_node_name [string]
heat_recovery_water_maximum_flow_rate [number]
exhaust_outlet_air_node_name [string]
heat_exchanger_calculation_method [string]
method_1_heat_exchanger_effectiveness [number]
method_2_parameter_hxs0 [number]
method_2_parameter_hxs1 [number]
method_2_parameter_hxs2 [number]
method_2_parameter_hxs3 [number]
method_2_parameter_hxs4 [number]
method_3_h0gas_coefficient [number]
method_3_ndotgasref_coefficient [number]
method_3_n_coefficient [number]
method_3_gas_area [number]
method_3_h0_water_coefficient [number]
method_3_n_dot_water_ref_coefficient [number]
method_3_m_coefficient [number]
method_3_water_area [number]
method_3_f_adjustment_factor [number]
method_4_hxl1_coefficient [number]
method_4_hxl2_coefficient [number]
method_4_condensation_threshold [number]
Generator:FuelCell:ElectricalStorage
Used to describe the electrical storage subsystem for a fuel cell power generator. The electrical storage model is a very simple “constrained bucket” model. Note that this electrical storage is embedded within the FC device.

Fields

choice_of_model [string]
nominal_charging_energetic_efficiency [number]
nominal_discharging_energetic_efficiency [number]
simple_maximum_capacity [number]
simple_maximum_power_draw [number]
simple_maximum_power_store [number]
initial_charge_state [number]
Generator:FuelCell:Inverter
Used to describe the power condition unit subsystem of a fuel cell power generator. This object models an inverter system contained within a fuel cell system that converts from direct current (DC) to alternating current (AC).

Fields

inverter_efficiency_calculation_mode [string]
inverter_efficiency [number]
efficiency_function_of_dc_power_curve_name [string]
Generator:FuelCell:StackCooler
This object is optional and is used to define details needed to model the stack cooler on PEMFC.

Fields

heat_recovery_water_inlet_node_name [string]
heat_recovery_water_outlet_node_name [string]
nominal_stack_temperature [number]
actual_stack_temperature [number]
coefficient_r0 [number]
coefficient_r1 [number]
coefficient_r2 [number]
coefficient_r3 [number]
stack_coolant_flow_rate [number]
stack_cooler_u_factor_times_area_value [number]
fs_cogen_adjustment_factor [number]
stack_cogeneration_exchanger_area [number]
stack_cogeneration_exchanger_nominal_flow_rate [number]
stack_cogeneration_exchanger_nominal_heat_transfer_coefficient [number]
stack_cogeneration_exchanger_nominal_heat_transfer_coefficient_exponent [number]
stack_cooler_pump_power [number]
stack_cooler_pump_heat_loss_fraction [number]
stack_air_cooler_fan_coefficient_f0 [number]
stack_air_cooler_fan_coefficient_f1 [number]
stack_air_cooler_fan_coefficient_f2 [number]
Generator:MicroCHP
Small-scale combined heat and power (micro CHP) electric generator using the model developed by IEA/ECBCS Annex 42 see www.cogen-sim.net. The model was developed for both internal combustion and Stirling cycle engines, but might be used for other types of residential CHP devices.

Fields

performance_parameters_name [string]
zone_name [string]
cooling_water_inlet_node_name [string]
cooling_water_outlet_node_name [string]
air_inlet_node_name [string]
air_outlet_node_name [string]
generator_fuel_supply_name [string]
availability_schedule_name [string]
Generator:MicroCHP:NonNormalizedParameters
This object is referenced by a Generator:MicroCHP object and provides the non-normalized parameters for the MicroCHP generator model.

Fields

maximum_electric_power [number]
minimum_electric_power [number]
minimum_cooling_water_flow_rate [number]
maximum_cooling_water_temperature [number]
electrical_efficiency_curve_name [string]
thermal_efficiency_curve_name [string]
cooling_water_flow_rate_mode [string]
cooling_water_flow_rate_curve_name [string]
air_flow_rate_curve_name [string]
maximum_net_electrical_power_rate_of_change [number]
maximum_fuel_flow_rate_of_change [number]
heat_exchanger_u_factor_times_area_value [number]
skin_loss_u_factor_times_area_value [number]
skin_loss_radiative_fraction [number]
aggregated_thermal_mass_of_energy_conversion_portion_of_generator [number]
aggregated_thermal_mass_of_heat_recovery_portion_of_generator [number]
standby_power [number]
warm_up_mode [string]
warm_up_fuel_flow_rate_coefficient [number]
nominal_engine_operating_temperature [number]
warm_up_power_coefficient [number]
warm_up_fuel_flow_rate_limit_ratio [number]
warm_up_delay_time [number]
cool_down_power [number]
cool_down_delay_time [number]
restart_mode [string]
Generator:FuelSupply
Used only with Generator:FuelCell and Generator:MicroCHP

Fields

fuel_temperature_modeling_mode [string]
fuel_temperature_reference_node_name [string]
fuel_temperature_schedule_name [string]
compressor_power_multiplier_function_of_fuel_rate_curve_name [string]
compressor_heat_loss_factor [number]
fuel_type [string]
liquid_generic_fuel_lower_heating_value [number]
liquid_generic_fuel_higher_heating_value [number]
liquid_generic_fuel_molecular_weight [number]
liquid_generic_fuel_co2_emission_factor [number]
number_of_constituents_in_gaseous_constituent_fuel_supply [number]
constituent_1_name [string]
constituent_1_molar_fraction [number]
constituent_2_name [string]
constituent_2_molar_fraction [number]
constituent_3_name [string]
constituent_3_molar_fraction [number]
constituent_4_name [string]
constituent_4_molar_fraction [number]
constituent_5_name [string]
constituent_5_molar_fraction [number]
constituent_6_name [string]
constituent_6_molar_fraction [number]
constituent_7_name [string]
constituent_7_molar_fraction [number]
constituent_8_name [string]
constituent_8_molar_fraction [number]
constituent_9_name [string]
constituent_9_molar_fraction [number]
constituent_10_name [string]
constituent_10_molar_fraction [number]
constituent_11_name [string]
constituent_11_molar_fraction [number]
constituent_12_name [string]
constituent_12_molar_fraction [number]
Generator:WindTurbine
Wind turbine generator.

Fields

availability_schedule_name [string]
rotor_type [string] (Default: HorizontalAxisWindTurbine)
power_control [string] (Default: VariableSpeedVariablePitch)
rated_rotor_speed [number]
rotor_diameter [number]
overall_height [number]
number_of_blades [number] (Default: 3.0)
rated_power [number]
rated_wind_speed [number]
cut_in_wind_speed [number]
cut_out_wind_speed [number]
fraction_system_efficiency [number] (Default: 0.835)
maximum_tip_speed_ratio [number] (Default: 5.0)
maximum_power_coefficient [number] (Default: 0.25)
annual_local_average_wind_speed [number]
height_for_local_average_wind_speed [number] (Default: 50.0)
blade_chord_area [number]
blade_drag_coefficient [number] (Default: 0.9)
blade_lift_coefficient [number] (Default: 0.05)
power_coefficient_c1 [number] (Default: 0.5176)
power_coefficient_c2 [number] (Default: 116.0)
power_coefficient_c3 [number] (Default: 0.4)
power_coefficient_c4 [number] (Default: 0.0)
power_coefficient_c5 [number] (Default: 5.0)
power_coefficient_c6 [number] (Default: 21.0)
ElectricLoadCenter:Generators
List of electric power generators to include in the simulation including the name and type of each generators along with availability schedule, rated power output, and thermal-to-electrical power ratio.

Fields

generator_outputs [Array of {generator_name, generator_object_type, generator_rated_electric_power_output, generator_availability_schedule_name, generator_rated_thermal_to_electrical_power_ratio}]
ElectricLoadCenter:Inverter:Simple
Electric power inverter to convert from direct current (DC) to alternating current (AC) in an electric load center that contains photovoltaic modules. This input object is for the simplest inverter model and uses a fixed efficiency.

Fields

availability_schedule_name [string]
zone_name [string]
radiative_fraction [number]
inverter_efficiency [number]
ElectricLoadCenter:Inverter:FunctionOfPower
Electric power inverter to convert from direct current (DC) to alternating current (AC) in an electric load center that contains photovoltaic modules. This input object is for an inverter model where efficiency is a function of normalized power.

Fields

availability_schedule_name [string]
zone_name [string]
radiative_fraction [number]
efficiency_function_of_power_curve_name [string]
rated_maximum_continuous_input_power [number]
minimum_efficiency [number]
maximum_efficiency [number]
minimum_power_output [number]
maximum_power_output [number]
ancillary_power_consumed_in_standby [number]
ElectricLoadCenter:Inverter:LookUpTable
California Energy Commission tests and publishes data on inverters This inverter model interpolates using CEC test data Input data are at http://www.gosolarcalifornia.org/equipment/inverter_tests/summaries

Fields

availability_schedule_name [string]
zone_name [string]
radiative_fraction [number]
rated_maximum_continuous_output_power [number]
night_tare_loss_power [number]
nominal_voltage_input [number]
efficiency_at_10_power_and_nominal_voltage [number]
efficiency_at_20_power_and_nominal_voltage [number]
efficiency_at_30_power_and_nominal_voltage [number]
efficiency_at_50_power_and_nominal_voltage [number]
efficiency_at_75_power_and_nominal_voltage [number]
efficiency_at_100_power_and_nominal_voltage [number]
ElectricLoadCenter:Storage:Simple
Used to model storage of electricity in an electric load center. This is a simple model that does not attempt to represent any of the characteristics of a real storage device such as a battery. The type of power, AC or DC, depends on the configuration chosen as the Electrical Buss Type in the ElectricLoadCenter:Distribution object.

Fields

availability_schedule_name [string]
zone_name [string]
radiative_fraction_for_zone_heat_gains [number]
nominal_energetic_efficiency_for_charging [number]
nominal_discharging_energetic_efficiency [number]
maximum_storage_capacity [number]
maximum_power_for_discharging [number]
maximum_power_for_charging [number]
initial_state_of_charge [number]
ElectricLoadCenter:Storage:Battery
Uses the kinetic battery model (KiBaM) to simulate rechargeable battery banks in an electrical load center. The battery bank is a collection of one or more individual battery modules. Given the surplus or deficit power from the electrical system and the state of charge from the previous time step, this object can model the voltage, current, and energy losses with charging and discharging during each time step. The cumulative battery damage can be also modeled and reported at the end of each simulation run.

Fields

availability_schedule_name [string]
zone_name [string]
radiative_fraction [number] (Default: 0.0)
number_of_battery_modules_in_parallel [number] (Default: 1.0)
number_of_battery_modules_in_series [number] (Default: 1.0)
maximum_module_capacity [number]
initial_fractional_state_of_charge [number] (Default: 1.0)
fraction_of_available_charge_capacity [number]
change_rate_from_bound_charge_to_available_charge [number]
fully_charged_module_open_circuit_voltage [number]
fully_discharged_module_open_circuit_voltage [number]
voltage_change_curve_name_for_charging [string]
voltage_change_curve_name_for_discharging [string]
module_internal_electrical_resistance [number]
maximum_module_discharging_current [number]
module_cut_off_voltage [number]
module_charge_rate_limit [number] (Default: 1.0)
battery_life_calculation [string] (Default: No)
number_of_cycle_bins [number] (Default: 10.0)
battery_life_curve_name [string]
ElectricLoadCenter:Storage:LiIonNMCBattery
Uses Lithium Ion NMC model to simulate rechargeable battery banks in an electrical load center. The battery bank is a collection of one or more individual battery modules. Given the surplus or deficit power from the electrical system and the state of charge from the previous time step, this object can model the voltage, current, and energy losses with charging and discharging during each time step. The cumulative battery damage can be also modeled and reported at the end of each simulation run.

Fields

availability_schedule_name [string]
zone_name [string]
radiative_fraction [number] (Default: 0.0)
lifetime_model [string] (Default: KandlerSmith)
number_of_cells_in_series [number]
number_of_strings_in_parallel [number]
initial_fractional_state_of_charge [number] (Default: 0.5)
dc_to_dc_charging_efficiency [number] (Default: 0.95)
battery_mass [number]
battery_surface_area [number]
battery_specific_heat_capacity [number] (Default: 1500.0)
heat_transfer_coefficient_between_battery_and_ambient [number] (Default: 7.5)
fully_charged_cell_voltage [number] (Default: 4.2)
cell_voltage_at_end_of_exponential_zone [number] (Default: 3.53)
cell_voltage_at_end_of_nominal_zone [number] (Default: 3.342)
default_nominal_cell_voltage [number] (Default: 3.342)
fully_charged_cell_capacity [number] (Default: 3.2)
fraction_of_cell_capacity_removed_at_the_end_of_exponential_zone [number] (Default: 0.8075)
fraction_of_cell_capacity_removed_at_the_end_of_nominal_zone [number] (Default: 0.976875)
charge_rate_at_which_voltage_vs_capacity_curve_was_generated [number] (Default: 1.0)
battery_cell_internal_electrical_resistance [number] (Default: 0.09)
ElectricLoadCenter:Transformer
a list of meters that can be reported are available after a run on the meter dictionary file (.mdd) if the Output:VariableDictionary has been requested.

Fields

availability_schedule_name [string]
transformer_usage [string] (Default: PowerInFromGrid)
zone_name [string]
radiative_fraction [number] (Default: 0.0)
rated_capacity [number]
phase [unknown field type] (Default: 3.0)
conductor_material [string] (Default: Aluminum)
full_load_temperature_rise [number] (Default: 150.0)
fraction_of_eddy_current_losses [number] (Default: 0.1)
performance_input_method [string] (Default: RatedLosses)
rated_no_load_loss [number]
rated_load_loss [number]
nameplate_efficiency [number] (Default: 0.98)
per_unit_load_for_nameplate_efficiency [number] (Default: 0.35)
reference_temperature_for_nameplate_efficiency [number] (Default: 75.0)
per_unit_load_for_maximum_efficiency [number]
consider_transformer_loss_for_utility_cost [string] (Default: Yes)
meters [Array of {meter_name}]
ElectricLoadCenter:Distribution
Describes a subpanel a list of meters that can be reported are available after a run on the meter dictionary file (.mdd) if the Output:VariableDictionary has been requested.

Fields

generator_list_name [string]
generator_operation_scheme_type [string]
generator_demand_limit_scheme_purchased_electric_demand_limit [number]
generator_track_schedule_name_scheme_schedule_name [string]
generator_track_meter_scheme_meter_name [string]
electrical_buss_type [string] (Default: AlternatingCurrent)
inverter_name [string]
electrical_storage_object_name [string]
transformer_object_name [string]
storage_operation_scheme [string] (Default: TrackFacilityElectricDemandStoreExcessOnSite)
storage_control_track_meter_name [string]
storage_converter_object_name [string]
maximum_storage_state_of_charge_fraction [number] (Default: 1.0)
minimum_storage_state_of_charge_fraction [number] (Default: 0.0)
design_storage_control_charge_power [number]
storage_charge_power_fraction_schedule_name [string]
design_storage_control_discharge_power [number]
storage_discharge_power_fraction_schedule_name [string]
storage_control_utility_demand_target [number]
storage_control_utility_demand_target_fraction_schedule_name [string]
ElectricLoadCenter:Storage:Converter
This model is for converting AC to DC for grid-supplied charging of DC storage

Fields

availability_schedule_name [string]
power_conversion_efficiency_method [string] (Default: SimpleFixed)
simple_fixed_efficiency [number] (Default: 0.95)
design_maximum_continuous_input_power [number]
efficiency_function_of_power_curve_name [string]
ancillary_power_consumed_in_standby [number]
zone_name [string]
radiative_fraction [number]
"""