"""
# Plant Heating and Cooling Equipment
"""
"""
Boiler:HotWater
This boiler model is an adaptation of the empirical model from the Building Loads and System Thermodynamics (BLAST) program. Boiler performance curves are generated by fitting catalog data to polynomial equations. A constant efficiency boiler may be modeled by leaving the normalized boiler efficiency curve name input blank.

Fields

fuel_type [string]
nominal_capacity [unknown field type]
nominal_thermal_efficiency [number]
efficiency_curve_temperature_evaluation_variable [string]
normalized_boiler_efficiency_curve_name [string]
design_water_flow_rate [unknown field type] (Default: Autosize)
minimum_part_load_ratio [number] (Default: 0.0)
maximum_part_load_ratio [number] (Default: 1.0)
optimum_part_load_ratio [number] (Default: 1.0)
boiler_water_inlet_node_name [string]
boiler_water_outlet_node_name [string]
water_outlet_upper_temperature_limit [number] (Default: 99.9)
boiler_flow_mode [string] (Default: NotModulated)
parasitic_electric_load [number] (Default: 0.0)
sizing_factor [number] (Default: 1.0)
end_use_subcategory [string] (Default: General)
Boiler:Steam
This boiler model is an adaptation of the empirical model from the Building Loads and System Thermodynamics (BLAST) program. Boiler performance curves are generated by fitting catalog data to third order polynomial equations. A constant efficiency boiler is modeled by setting the fuel use coefficients as follows: N9=1, N10=0, N11=0

Fields

fuel_type [string]
maximum_operating_pressure [number] (Default: 160000.0)
theoretical_efficiency [number] (Default: 0.8)
design_outlet_steam_temperature [number] (Default: 100.0)
nominal_capacity [unknown field type]
minimum_part_load_ratio [number]
maximum_part_load_ratio [number]
optimum_part_load_ratio [number]
coefficient_1_of_fuel_use_function_of_part_load_ratio_curve [number]
coefficient_2_of_fuel_use_function_of_part_load_ratio_curve [number]
coefficient_3_of_fuel_use_function_of_part_load_ratio_curve [number]
water_inlet_node_name [string]
steam_outlet_node_name [string]
sizing_factor [number] (Default: 1.0)
end_use_subcategory [string] (Default: General)
Chiller:Electric:EIR
This chiller model is the empirical model from the DOE-2 building Energy simulation program. Chiller performance at off-reference conditions is modeled using three polynomial equations. Three curves objects are required.

Fields

reference_capacity [unknown field type]
reference_cop [number]
reference_leaving_chilled_water_temperature [number] (Default: 6.67)
reference_entering_condenser_fluid_temperature [number] (Default: 29.4)
reference_chilled_water_flow_rate [unknown field type]
reference_condenser_fluid_flow_rate [unknown field type]
cooling_capacity_function_of_temperature_curve_name [string]
electric_input_to_cooling_output_ratio_function_of_temperature_curve_name [string]
electric_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name [string]
minimum_part_load_ratio [number] (Default: 0.1)
maximum_part_load_ratio [number] (Default: 1.0)
optimum_part_load_ratio [number] (Default: 1.0)
minimum_unloading_ratio [number] (Default: 0.2)
chilled_water_inlet_node_name [string]
chilled_water_outlet_node_name [string]
condenser_inlet_node_name [string]
condenser_outlet_node_name [string]
condenser_type [string] (Default: WaterCooled)
condenser_fan_power_ratio [number] (Default: 0.0)
fraction_of_compressor_electric_consumption_rejected_by_condenser [number] (Default: 1.0)
leaving_chilled_water_lower_temperature_limit [number] (Default: 2.0)
chiller_flow_mode [string] (Default: NotModulated)
design_heat_recovery_water_flow_rate [unknown field type] (Default: 0.0)
heat_recovery_inlet_node_name [string]
heat_recovery_outlet_node_name [string]
sizing_factor [number] (Default: 1.0)
basin_heater_capacity [number] (Default: 0.0)
basin_heater_setpoint_temperature [number] (Default: 2.0)
basin_heater_operating_schedule_name [string]
condenser_heat_recovery_relative_capacity_fraction [number]
heat_recovery_inlet_high_temperature_limit_schedule_name [string]
heat_recovery_leaving_temperature_setpoint_node_name [string]
end_use_subcategory [string] (Default: General)
Chiller:Electric:ReformulatedEIR
This chiller model is an empirical model, a reformulated version of Chiller:Electric:EIR where the performance is a function of condenser leaving fluid Temperature instead of condenser entering fluid Temperature. Chiller performance at off-reference conditions is modeled using three polynomial equations. Three curve objects are required.

Fields

reference_capacity [unknown field type]
reference_cop [number]
reference_leaving_chilled_water_temperature [number] (Default: 6.67)
reference_leaving_condenser_water_temperature [number] (Default: 35.0)
reference_chilled_water_flow_rate [unknown field type]
reference_condenser_water_flow_rate [unknown field type]
cooling_capacity_function_of_temperature_curve_name [string]
electric_input_to_cooling_output_ratio_function_of_temperature_curve_name [string]
electric_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_type [string] (Default: LeavingCondenserWaterTemperature)
electric_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name [string]
minimum_part_load_ratio [number] (Default: 0.1)
maximum_part_load_ratio [number] (Default: 1.0)
optimum_part_load_ratio [number] (Default: 1.0)
minimum_unloading_ratio [number] (Default: 0.2)
chilled_water_inlet_node_name [string]
chilled_water_outlet_node_name [string]
condenser_inlet_node_name [string]
condenser_outlet_node_name [string]
fraction_of_compressor_electric_consumption_rejected_by_condenser [number] (Default: 1.0)
leaving_chilled_water_lower_temperature_limit [number] (Default: 2.0)
chiller_flow_mode_type [string] (Default: NotModulated)
design_heat_recovery_water_flow_rate [unknown field type] (Default: 0.0)
heat_recovery_inlet_node_name [string]
heat_recovery_outlet_node_name [string]
sizing_factor [number] (Default: 1.0)
condenser_heat_recovery_relative_capacity_fraction [number]
heat_recovery_inlet_high_temperature_limit_schedule_name [string]
heat_recovery_leaving_temperature_setpoint_node_name [string]
end_use_subcategory [string] (Default: General)
Chiller:Electric
This chiller model is the empirical model from the Building Loads and System Thermodynamics (BLAST) program. Chiller performance curves are generated by fitting catalog data to third order polynomial equations. Three sets of coefficients are required.

Fields

condenser_type [string] (Default: AirCooled)
nominal_capacity [unknown field type]
nominal_cop [number]
chilled_water_inlet_node_name [string]
chilled_water_outlet_node_name [string]
condenser_inlet_node_name [string]
condenser_outlet_node_name [string]
minimum_part_load_ratio [number]
maximum_part_load_ratio [number]
optimum_part_load_ratio [number]
design_condenser_inlet_temperature [number]
temperature_rise_coefficient [number]
design_chilled_water_outlet_temperature [number]
design_chilled_water_flow_rate [unknown field type]
design_condenser_fluid_flow_rate [unknown field type]
coefficient_1_of_capacity_ratio_curve [number]
coefficient_2_of_capacity_ratio_curve [number]
coefficient_3_of_capacity_ratio_curve [number]
coefficient_1_of_power_ratio_curve [number]
coefficient_2_of_power_ratio_curve [number]
coefficient_3_of_power_ratio_curve [number]
coefficient_1_of_full_load_ratio_curve [number]
coefficient_2_of_full_load_ratio_curve [number]
coefficient_3_of_full_load_ratio_curve [number]
chilled_water_outlet_temperature_lower_limit [number]
chiller_flow_mode [string] (Default: NotModulated)
design_heat_recovery_water_flow_rate [unknown field type] (Default: 0.0)
heat_recovery_inlet_node_name [string]
heat_recovery_outlet_node_name [string]
sizing_factor [number] (Default: 1.0)
basin_heater_capacity [number] (Default: 0.0)
basin_heater_setpoint_temperature [number] (Default: 2.0)
basin_heater_operating_schedule_name [string]
condenser_heat_recovery_relative_capacity_fraction [number]
heat_recovery_inlet_high_temperature_limit_schedule_name [string]
heat_recovery_leaving_temperature_setpoint_node_name [string]
end_use_subcategory [string] (Default: General)
Chiller:Absorption:Indirect
This indirect absorption chiller model is an enhanced model from the Building Loads and System Thermodynamics (BLAST) program. Chiller performance curves are generated by fitting catalog data to third order polynomial equations. The chiller capacity is a function of condenser, chilled water, and generator temperatures. The heat input is a function of part-load ratio, condenser temperature, and chilled water temperature.

Fields

nominal_capacity [unknown field type]
nominal_pumping_power [unknown field type]
chilled_water_inlet_node_name [string]
chilled_water_outlet_node_name [string]
condenser_inlet_node_name [string]
condenser_outlet_node_name [string]
minimum_part_load_ratio [number]
maximum_part_load_ratio [number]
optimum_part_load_ratio [number]
design_condenser_inlet_temperature [number] (Default: 30.0)
condenser_inlet_temperature_lower_limit [number] (Default: 15.0)
chilled_water_outlet_temperature_lower_limit [number] (Default: 5.0)
design_chilled_water_flow_rate [unknown field type] (Default: Autosize)
design_condenser_water_flow_rate [unknown field type] (Default: Autosize)
chiller_flow_mode [string] (Default: NotModulated)
generator_heat_input_function_of_part_load_ratio_curve_name [string]
pump_electric_input_function_of_part_load_ratio_curve_name [string]
generator_inlet_node_name [string]
generator_outlet_node_name [string]
capacity_correction_function_of_condenser_temperature_curve_name [string]
capacity_correction_function_of_chilled_water_temperature_curve_name [string]
capacity_correction_function_of_generator_temperature_curve_name [string]
generator_heat_input_correction_function_of_condenser_temperature_curve_name [string]
generator_heat_input_correction_function_of_chilled_water_temperature_curve_name [string]
generator_heat_source_type [string] (Default: Steam)
design_generator_fluid_flow_rate [unknown field type]
temperature_lower_limit_generator_inlet [number] (Default: 0.0)
degree_of_subcooling_in_steam_generator [number] (Default: 1.0)
degree_of_subcooling_in_steam_condensate_loop [number] (Default: 0.0)
sizing_factor [number] (Default: 1.0)
Chiller:Absorption
This indirect absorption chiller model is the empirical model from the Building Loads and System Thermodynamics (BLAST) program. Chiller performance curves are generated by fitting catalog data to third order polynomial equations. Two sets of coefficients are required.

Fields

nominal_capacity [unknown field type]
nominal_pumping_power [unknown field type]
chilled_water_inlet_node_name [string]
chilled_water_outlet_node_name [string]
condenser_inlet_node_name [string]
condenser_outlet_node_name [string]
minimum_part_load_ratio [number]
maximum_part_load_ratio [number]
optimum_part_load_ratio [number]
design_condenser_inlet_temperature [number]
design_chilled_water_flow_rate [unknown field type]
design_condenser_water_flow_rate [unknown field type]
coefficient_1_of_the_hot_water_or_steam_use_part_load_ratio_curve [number]
coefficient_2_of_the_hot_water_or_steam_use_part_load_ratio_curve [number]
coefficient_3_of_the_hot_water_or_steam_use_part_load_ratio_curve [number]
coefficient_1_of_the_pump_electric_use_part_load_ratio_curve [number]
coefficient_2_of_the_pump_electric_use_part_load_ratio_curve [number]
coefficient_3_of_the_pump_electric_use_part_load_ratio_curve [number]
chilled_water_outlet_temperature_lower_limit [number]
generator_inlet_node_name [string]
generator_outlet_node_name [string]
chiller_flow_mode [string] (Default: NotModulated)
generator_heat_source_type [string] (Default: Steam)
design_generator_fluid_flow_rate [unknown field type]
degree_of_subcooling_in_steam_generator [number] (Default: 1.0)
sizing_factor [number] (Default: 1.0)
Chiller:ConstantCOP
This constant COP chiller model provides a means of quickly specifying a Chiller where performance data is not available.

Fields

nominal_capacity [unknown field type]
nominal_cop [number]
design_chilled_water_flow_rate [unknown field type]
design_condenser_water_flow_rate [unknown field type]
chilled_water_inlet_node_name [string]
chilled_water_outlet_node_name [string]
condenser_inlet_node_name [string]
condenser_outlet_node_name [string]
condenser_type [string] (Default: AirCooled)
chiller_flow_mode [string] (Default: NotModulated)
sizing_factor [number] (Default: 1.0)
basin_heater_capacity [number] (Default: 0.0)
basin_heater_setpoint_temperature [number] (Default: 2.0)
basin_heater_operating_schedule_name [string]
Chiller:EngineDriven
This chiller model is the empirical model from the Building Loads and System Thermodynamics (BLAST) program. Chiller performance curves are generated by fitting catalog data to third order polynomial equations. Three sets of coefficients are required.

Fields

condenser_type [string] (Default: AirCooled)
nominal_capacity [unknown field type]
nominal_cop [number]
chilled_water_inlet_node_name [string]
chilled_water_outlet_node_name [string]
condenser_inlet_node_name [string]
condenser_outlet_node_name [string]
minimum_part_load_ratio [number]
maximum_part_load_ratio [number]
optimum_part_load_ratio [number]
design_condenser_inlet_temperature [number]
temperature_rise_coefficient [number]
design_chilled_water_outlet_temperature [number]
design_chilled_water_flow_rate [unknown field type]
design_condenser_water_flow_rate [unknown field type]
coefficient_1_of_capacity_ratio_curve [number]
coefficient_2_of_capacity_ratio_curve [number]
coefficient_3_of_capacity_ratio_curve [number]
coefficient_1_of_power_ratio_curve [number]
coefficient_2_of_power_ratio_curve [number]
coefficient_3_of_power_ratio_curve [number]
coefficient_1_of_full_load_ratio_curve [number]
coefficient_2_of_full_load_ratio_curve [number]
coefficient_3_of_full_load_ratio_curve [number]
chilled_water_outlet_temperature_lower_limit [number]
fuel_use_curve_name [string]
jacket_heat_recovery_curve_name [string]
lube_heat_recovery_curve_name [string]
total_exhaust_energy_curve_name [string]
exhaust_temperature_curve_name [string]
coefficient_1_of_u_factor_times_area_curve [number]
coefficient_2_of_u_factor_times_area_curve [number]
maximum_exhaust_flow_per_unit_of_power_output [number]
design_minimum_exhaust_temperature [number]
fuel_type [string]
fuel_higher_heating_value [number]
design_heat_recovery_water_flow_rate [unknown field type] (Default: 0.0)
heat_recovery_inlet_node_name [string]
heat_recovery_outlet_node_name [string]
chiller_flow_mode [string] (Default: NotModulated)
maximum_temperature_for_heat_recovery_at_heat_recovery_outlet_node [number] (Default: 60.0)
sizing_factor [number] (Default: 1.0)
basin_heater_capacity [number] (Default: 0.0)
basin_heater_setpoint_temperature [number] (Default: 2.0)
basin_heater_operating_schedule_name [string]
condenser_heat_recovery_relative_capacity_fraction [number]
Chiller:CombustionTurbine
This chiller model is the empirical model from the Building Loads and System Thermodynamics (BLAST) program. Chiller performance curves are generated by fitting catalog data to third order polynomial equations. Three sets of coefficients are required.

Fields

condenser_type [string] (Default: AirCooled)
nominal_capacity [unknown field type]
nominal_cop [number]
chilled_water_inlet_node_name [string]
chilled_water_outlet_node_name [string]
condenser_inlet_node_name [string]
condenser_outlet_node_name [string]
minimum_part_load_ratio [number]
maximum_part_load_ratio [number]
optimum_part_load_ratio [number]
design_condenser_inlet_temperature [number]
temperature_rise_coefficient [number]
design_chilled_water_outlet_temperature [number]
design_chilled_water_flow_rate [unknown field type]
design_condenser_water_flow_rate [unknown field type]
coefficient_1_of_capacity_ratio_curve [number]
coefficient_2_of_capacity_ratio_curve [number]
coefficient_3_of_capacity_ratio_curve [number]
coefficient_1_of_power_ratio_curve [number]
coefficient_2_of_power_ratio_curve [number]
coefficient_3_of_power_ratio_curve [number]
coefficient_1_of_full_load_ratio_curve [number]
coefficient_2_of_full_load_ratio_curve [number]
coefficient_3_of_full_load_ratio_curve [number]
chilled_water_outlet_temperature_lower_limit [number]
coefficient_1_of_fuel_input_curve [number]
coefficient_2_of_fuel_input_curve [number]
coefficient_3_of_fuel_input_curve [number]
coefficient_1_of_temperature_based_fuel_input_curve [number]
coefficient_2_of_temperature_based_fuel_input_curve [number]
coefficient_3_of_temperature_based_fuel_input_curve [number]
coefficient_1_of_exhaust_flow_curve [number]
coefficient_2_of_exhaust_flow_curve [number]
coefficient_3_of_exhaust_flow_curve [number]
coefficient_1_of_exhaust_gas_temperature_curve [number]
coefficient_2_of_exhaust_gas_temperature_curve [number]
coefficient_3_of_exhaust_gas_temperature_curve [number]
coefficient_1_of_temperature_based_exhaust_gas_temperature_curve [number]
coefficient_2_of_temperature_based_exhaust_gas_temperature_curve [number]
coefficient_3_of_temperature_based_exhaust_gas_temperature_curve [number]
coefficient_1_of_recovery_lube_heat_curve [number]
coefficient_2_of_recovery_lube_heat_curve [number]
coefficient_3_of_recovery_lube_heat_curve [number]
coefficient_1_of_u_factor_times_area_curve [number]
coefficient_2_of_u_factor_times_area_curve [number]
gas_turbine_engine_capacity [unknown field type]
maximum_exhaust_flow_per_unit_of_power_output [number]
design_steam_saturation_temperature [number]
fuel_higher_heating_value [number]
design_heat_recovery_water_flow_rate [unknown field type] (Default: 0.0)
heat_recovery_inlet_node_name [string]
heat_recovery_outlet_node_name [string]
chiller_flow_mode [string] (Default: NotModulated)
fuel_type [string] (Default: NaturalGas)
heat_recovery_maximum_temperature [number] (Default: 80.0)
sizing_factor [number] (Default: 1.0)
basin_heater_capacity [number] (Default: 0.0)
basin_heater_setpoint_temperature [number] (Default: 2.0)
basin_heater_operating_schedule_name [string]
condenser_heat_recovery_relative_capacity_fraction [number]
turbine_engine_efficiency [number] (Default: 0.35)
ChillerHeater:Absorption:DirectFired
Direct fired gas absorption chiller-heater using performance curves similar to DOE-2

Fields

nominal_cooling_capacity [unknown field type] (Default: Autosize)
heating_to_cooling_capacity_ratio [number] (Default: 0.8)
fuel_input_to_cooling_output_ratio [number] (Default: 0.97)
fuel_input_to_heating_output_ratio [number] (Default: 1.25)
electric_input_to_cooling_output_ratio [number] (Default: 0.01)
electric_input_to_heating_output_ratio [number] (Default: 0.0)
chilled_water_inlet_node_name [string]
chilled_water_outlet_node_name [string]
condenser_inlet_node_name [string]
condenser_outlet_node_name [string]
hot_water_inlet_node_name [string]
hot_water_outlet_node_name [string]
minimum_part_load_ratio [number] (Default: 0.1)
maximum_part_load_ratio [number] (Default: 1.0)
optimum_part_load_ratio [number] (Default: 1.0)
design_entering_condenser_water_temperature [number] (Default: 29.0)
design_leaving_chilled_water_temperature [number] (Default: 7.0)
design_chilled_water_flow_rate [unknown field type] (Default: Autosize)
design_condenser_water_flow_rate [unknown field type] (Default: Autosize)
design_hot_water_flow_rate [unknown field type] (Default: Autosize)
cooling_capacity_function_of_temperature_curve_name [string]
fuel_input_to_cooling_output_ratio_function_of_temperature_curve_name [string]
fuel_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name [string]
electric_input_to_cooling_output_ratio_function_of_temperature_curve_name [string]
electric_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name [string]
heating_capacity_function_of_cooling_capacity_curve_name [string]
fuel_input_to_heat_output_ratio_during_heating_only_operation_curve_name [string]
temperature_curve_input_variable [string] (Default: EnteringCondenser)
condenser_type [string] (Default: WaterCooled)
chilled_water_temperature_lower_limit [number] (Default: 2.0)
fuel_higher_heating_value [number] (Default: 0.0)
fuel_type [string] (Default: NaturalGas)
sizing_factor [number] (Default: 1.0)
ChillerHeater:Absorption:DoubleEffect
Exhaust fired absorption chiller-heater using performance curves similar to DOE-2

Fields

nominal_cooling_capacity [unknown field type] (Default: Autosize)
heating_to_cooling_capacity_ratio [number] (Default: 0.8)
thermal_energy_input_to_cooling_output_ratio [number] (Default: 0.97)
thermal_energy_input_to_heating_output_ratio [number] (Default: 1.25)
electric_input_to_cooling_output_ratio [number] (Default: 0.01)
electric_input_to_heating_output_ratio [number] (Default: 0.0)
chilled_water_inlet_node_name [string]
chilled_water_outlet_node_name [string]
condenser_inlet_node_name [string]
condenser_outlet_node_name [string]
hot_water_inlet_node_name [string]
hot_water_outlet_node_name [string]
minimum_part_load_ratio [number] (Default: 0.1)
maximum_part_load_ratio [number] (Default: 1.0)
optimum_part_load_ratio [number] (Default: 1.0)
design_entering_condenser_water_temperature [number] (Default: 29.0)
design_leaving_chilled_water_temperature [number] (Default: 7.0)
design_chilled_water_flow_rate [unknown field type] (Default: Autosize)
design_condenser_water_flow_rate [unknown field type] (Default: Autosize)
design_hot_water_flow_rate [unknown field type] (Default: Autosize)
cooling_capacity_function_of_temperature_curve_name [string]
fuel_input_to_cooling_output_ratio_function_of_temperature_curve_name [string]
fuel_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name [string]
electric_input_to_cooling_output_ratio_function_of_temperature_curve_name [string]
electric_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name [string]
heating_capacity_function_of_cooling_capacity_curve_name [string]
fuel_input_to_heat_output_ratio_during_heating_only_operation_curve_name [string]
temperature_curve_input_variable [string] (Default: EnteringCondenser)
condenser_type [string] (Default: WaterCooled)
chilled_water_temperature_lower_limit [number] (Default: 2.0)
exhaust_source_object_type [string]
exhaust_source_object_name [string]
sizing_factor [number] (Default: 1.0)
HeatPump:PlantLoop:EIR:Cooling
An EIR formulated water to water heat pump model, cooling operation.

Fields

load_side_inlet_node_name [string]
load_side_outlet_node_name [string]
condenser_type [string] (Default: WaterSource)
source_side_inlet_node_name [string]
source_side_outlet_node_name [string]
companion_heat_pump_name [string]
load_side_reference_flow_rate [unknown field type] (Default: Autosize)
source_side_reference_flow_rate [unknown field type] (Default: Autosize)
reference_capacity [unknown field type] (Default: Autosize)
reference_coefficient_of_performance [number] (Default: 7.5)
sizing_factor [number] (Default: 1.0)
capacity_modifier_function_of_temperature_curve_name [string]
electric_input_to_output_ratio_modifier_function_of_temperature_curve_name [string]
electric_input_to_output_ratio_modifier_function_of_part_load_ratio_curve_name [string]
HeatPump:PlantLoop:EIR:Heating
An EIR formulated water to water heat pump model, heating operation

Fields

load_side_inlet_node_name [string]
load_side_outlet_node_name [string]
condenser_type [string] (Default: WaterSource)
source_side_inlet_node_name [string]
source_side_outlet_node_name [string]
companion_heat_pump_name [string]
load_side_reference_flow_rate [unknown field type] (Default: Autosize)
source_side_reference_flow_rate [unknown field type] (Default: Autosize)
reference_capacity [unknown field type] (Default: Autosize)
reference_coefficient_of_performance [number] (Default: 7.5)
sizing_factor [number] (Default: 1.0)
capacity_modifier_function_of_temperature_curve_name [string]
electric_input_to_output_ratio_modifier_function_of_temperature_curve_name [string]
electric_input_to_output_ratio_modifier_function_of_part_load_ratio_curve_name [string]
HeatPump:WaterToWater:EquationFit:Heating
simple water-water hp curve-fit model

Fields

source_side_inlet_node_name [string]
source_side_outlet_node_name [string]
load_side_inlet_node_name [string]
load_side_outlet_node_name [string]
reference_load_side_flow_rate [unknown field type]
reference_source_side_flow_rate [unknown field type]
reference_heating_capacity [unknown field type]
reference_heating_power_consumption [unknown field type]
heating_capacity_curve_name [string]
heating_compressor_power_curve_name [string]
reference_coefficient_of_performance [number] (Default: 7.5)
sizing_factor [number] (Default: 1.0)
companion_cooling_heat_pump_name [string]
HeatPump:WaterToWater:EquationFit:Cooling
simple water-water heat pump curve-fit model

Fields

source_side_inlet_node_name [string]
source_side_outlet_node_name [string]
load_side_inlet_node_name [string]
load_side_outlet_node_name [string]
reference_load_side_flow_rate [unknown field type]
reference_source_side_flow_rate [unknown field type]
reference_cooling_capacity [unknown field type]
reference_cooling_power_consumption [unknown field type]
cooling_capacity_curve_name [string]
cooling_compressor_power_curve_name [string]
reference_coefficient_of_performance [number] (Default: 8.0)
sizing_factor [number] (Default: 1.0)
companion_heating_heat_pump_name [string]
HeatPump:WaterToWater:ParameterEstimation:Cooling
OSU parameter estimation model

Fields

source_side_inlet_node_name [string]
source_side_outlet_node_name [string]
load_side_inlet_node_name [string]
load_side_outlet_node_name [string]
nominal_cop [number]
nominal_capacity [number]
minimum_part_load_ratio [number]
maximum_part_load_ratio [number]
optimum_part_load_ratio [number]
load_side_flow_rate [number]
source_side_flow_rate [number]
load_side_heat_transfer_coefficient [number]
source_side_heat_transfer_coefficient [number]
piston_displacement [number]
compressor_clearance_factor [number]
compressor_suction_and_discharge_pressure_drop [number]
superheating [number]
constant_part_of_electromechanical_power_losses [number]
loss_factor [number]
high_pressure_cut_off [number] (Default: 500000000.0)
low_pressure_cut_off [number] (Default: 0.0)
HeatPump:WaterToWater:ParameterEstimation:Heating
OSU parameter estimation model

Fields

source_side_inlet_node_name [string]
source_side_outlet_node_name [string]
load_side_inlet_node_name [string]
load_side_outlet_node_name [string]
nominal_cop [number]
nominal_capacity [number]
minimum_part_load_ratio [number]
maximum_part_load_ratio [number]
optimum_part_load_ratio [number]
load_side_flow_rate [number]
source_side_flow_rate [number]
load_side_heat_transfer_coefficient [number]
source_side_heat_transfer_coefficient [number]
piston_displacement [number]
compressor_clearance_factor [number]
compressor_suction_and_discharge_pressure_drop [number]
superheating [number]
constant_part_of_electromechanical_power_losses [number]
loss_factor [number]
high_pressure_cut_off [number] (Default: 500000000.0)
low_pressure_cut_off [number] (Default: 0.0)
DistrictCooling
Centralized source of chilled water, such as a district cooling system.

Fields

chilled_water_inlet_node_name [string]
chilled_water_outlet_node_name [string]
nominal_capacity [unknown field type]
capacity_fraction_schedule_name [string]
DistrictHeating
Centralized source of hot water, such as a district heating system.

Fields

hot_water_inlet_node_name [string]
hot_water_outlet_node_name [string]
nominal_capacity [unknown field type]
capacity_fraction_schedule_name [string]
PlantComponent:TemperatureSource
Simulates an object of pre-determined (constant or scheduled) source temperature The object introduces fluid into the plant loop at the specified temperature and at the same flow rate as the fluid enters the component Fluid entering the component vanishes equivalent to the relief air in an air system

Fields

inlet_node [string]
outlet_node [string]
design_volume_flow_rate [unknown field type]
temperature_specification_type [string]
source_temperature [number]
source_temperature_schedule_name [string]
CentralHeatPumpSystem
This chiller bank can contain multiple chiller heaters and heat pump performance objects. Its function is to encapsulate the extra controls needed to turn individual modules on/off and whether they are to operate in cooling-only, heating-only or simultaneous cooling/heating mode and whether to connect the source water to the evaporator or condenser side.

Fields

control_method [string] (Default: SmartMixing)
cooling_loop_inlet_node_name [string]
cooling_loop_outlet_node_name [string]
source_loop_inlet_node_name [string]
source_loop_outlet_node_name [string]
heating_loop_inlet_node_name [string]
heating_loop_outlet_node_name [string]
ancillary_power [number] (Default: 0.0)
ancillary_operation_schedule_name [string]
chiller_heater_modules_performance_component_object_type_1 [string]
chiller_heater_modules_performance_component_name_1 [string]
chiller_heater_modules_control_schedule_name_1 [string]
number_of_chiller_heater_modules_1 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_2 [string]
chiller_heater_modules_performance_component_name_2 [string]
chiller_heater_modules_control_schedule_name_2 [string]
number_of_chiller_heater_modules_2 [number] (Default: 1.0)
chiller_heater_performance_component_object_type_3 [string]
chiller_heater_performance_component_name_3 [string]
chiller_heater_modules_control_schedule_name_3 [string]
number_of_chiller_heater_modules_3 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_4 [string]
chiller_heater_modules_performance_component_name_4 [string]
chiller_heater_modules_control_schedule_name_4 [string]
number_of_chiller_heater_modules_4 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_5 [string]
chiller_heater_models_performance_component_name_5 [string]
chiller_heater_modules_control_schedule_name_5 [string]
number_of_chiller_heater_modules_5 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_6 [string]
chiller_heater_modules_performance_component_name_6 [string]
chiller_heater_modules_control_schedule_name_6 [string]
number_of_chiller_heater_modules_6 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_7 [string]
chiller_heater_modules_performance_component_name_7 [string]
chiller_heater_modules_control_schedule_name_7 [string]
number_of_chiller_heater_modules_7 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_8 [string]
chiller_heater_modules_performance_component_name_8 [string]
chiller_heater_modules_control_schedule_name_8 [string]
number_of_chiller_heater_modules_8 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_9 [string]
chiller_heater_modules_performance_component_name_9 [string]
chiller_heater_modules_control_schedule_name_9 [string]
number_of_chiller_heater_modules_9 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_10 [string]
chiller_heater_modules_performance_component_name_10 [string]
chiller_heater_modules_control_schedule_name_10 [string]
number_of_chiller_heater_modules_10 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_11 [string]
chiller_heater_modules_performance_component_name_11 [string]
chiller_heater_module_control_schedule_name_11 [string]
number_of_chiller_heater_modules_11 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_12 [string]
chiller_heater_modules_performance_component_name_12 [string]
chiller_heater_modules_control_schedule_name_12 [string]
number_of_chiller_heater_modules_12 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_13 [string]
chiller_heater_modules_performance_component_name_13 [string]
chiller_heater_modules_control_schedule_name_13 [string]
number_of_chiller_heater_modules_13 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_14 [string]
chiller_heater_modules_performance_component_name_14 [string]
chiller_heater_modules_control_schedule_name_14 [string]
number_of_chiller_heater_modules_14 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_15 [string]
chiller_heater_modules_performance_component_name_15 [string]
chiller_heater_modules_control_schedule_name_15 [string]
number_of_chiller_heater_modules_15 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_16 [string]
chiller_heater_modules_performance_component_name_16 [string]
chiller_heater_modules_control_schedule_name_16 [string]
number_of_chiller_heater_modules_16 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_17 [string]
chiller_heater_modules_performance_component_name_17 [string]
chiller_heater_modules_control_schedule_name_17 [string]
number_of_chiller_heater_modules_17 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_18 [string]
chiller_heater_modules_performance_component_name_18 [string]
chiller_heater_modules_control_control_schedule_name_18 [string]
number_of_chiller_heater_modules_18 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_19 [string]
chiller_heater_modules_performance_component_name_19 [string]
chiller_heater_modules_control_schedule_name_19 [string]
number_of_chiller_heater_modules_19 [number] (Default: 1.0)
chiller_heater_modules_performance_component_object_type_20 [string]
chiller_heater_modules_performance_component_name_20 [string]
chiller_heater_modules_control_schedule_name_20 [string]
number_of_chiller_heater_modules_20 [number] (Default: 1.0)
ChillerHeaterPerformance:Electric:EIR
This chiller model is a generic chiller-heater where the cooling mode performance is a function of condenser entering or leaving fluid temperature and the heating mode performance is typically a function of condenser leaving fluid temperature. Performance at off-reference conditions is modeled using three polynomial equations per mode. Six curve objects are required.

Fields

reference_cooling_mode_evaporator_capacity [unknown field type]
reference_cooling_mode_cop [number]
reference_cooling_mode_leaving_chilled_water_temperature [number] (Default: 6.67)
reference_cooling_mode_entering_condenser_fluid_temperature [number] (Default: 29.44)
reference_cooling_mode_leaving_condenser_water_temperature [number] (Default: 35.0)
reference_heating_mode_cooling_capacity_ratio [number] (Default: 0.75)
reference_heating_mode_cooling_power_input_ratio [number] (Default: 1.38)
reference_heating_mode_leaving_chilled_water_temperature [number] (Default: 6.67)
reference_heating_mode_leaving_condenser_water_temperature [number] (Default: 49.0)
reference_heating_mode_entering_condenser_fluid_temperature [number] (Default: 29.44)
heating_mode_entering_chilled_water_temperature_low_limit [number] (Default: 12.22)
chilled_water_flow_mode_type [string] (Default: ConstantFlow)
design_chilled_water_flow_rate [unknown field type]
design_condenser_water_flow_rate [unknown field type]
design_hot_water_flow_rate [number] (Default: 0.0)
compressor_motor_efficiency [number] (Default: 1.0)
condenser_type [string] (Default: WaterCooled)
cooling_mode_temperature_curve_condenser_water_independent_variable [string] (Default: EnteringCondenser)
cooling_mode_cooling_capacity_function_of_temperature_curve_name [string]
cooling_mode_electric_input_to_cooling_output_ratio_function_of_temperature_curve_name [string]
cooling_mode_electric_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name [string]
cooling_mode_cooling_capacity_optimum_part_load_ratio [number] (Default: 1.0)
heating_mode_temperature_curve_condenser_water_independent_variable [string] (Default: LeavingCondenser)
heating_mode_cooling_capacity_function_of_temperature_curve_name [string]
heating_mode_electric_input_to_cooling_output_ratio_function_of_temperature_curve_name [string]
heating_mode_electric_input_to_cooling_output_ratio_function_of_part_load_ratio_curve_name [string]
heating_mode_cooling_capacity_optimum_part_load_ratio [number] (Default: 1.0)
sizing_factor [number] (Default: 1.0)
"""